import { useState } from "react";
import { Activity, Bot, Check, ChevronRight, CircleAlert, Crosshair, Gauge, Layers3, LockKeyhole, Pause, Play, Plus, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Target, WifiOff } from "lucide-react";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { useMt5Status } from "@/hooks/use-mt5";
import { cn } from "@/lib/utils";

const strategyTemplates = [
  { name: "Trend Following", description: "Follows confirmed momentum across selected symbols and timeframes.", icon: Activity, color: "text-primary" },
  { name: "Mean Reversion", description: "Looks for statistically stretched moves before planning an entry.", icon: Crosshair, color: "text-purple" },
  { name: "Breakout Scanner", description: "Monitors volatility expansion and waits for a confirmed range break.", icon: Target, color: "text-warning" },
];

export default function Strategies() {
  const { data: status } = useMt5Status();
  const connected = status?.state === "connected";
  const [enabled, setEnabled] = useState<Record<string, boolean>>({});
  const [risk, setRisk] = useState("1.00");
  const [timeframe, setTimeframe] = useState("M15");
  const [symbols, setSymbols] = useState("XAUUSDm, EURUSDm");

  return <DashboardLayout><div className="mx-auto max-w-[1500px] space-y-5">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-primary"><Sparkles className="h-3.5 w-3.5" /> STRATEGY LAB</div><h1 className="text-2xl font-extrabold tracking-tight md:text-3xl">AI Strategies</h1><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Configure signal engines and execution rules. Live signals remain disabled until a verified MT5 account is connected.</p></div><div className={cn("flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold", connected ? "border-success/30 bg-success/10 text-success" : "border-border bg-card text-muted-foreground")}>{connected ? <ShieldCheck className="h-4 w-4" /> : <WifiOff className="h-4 w-4" />}{connected ? "MT5 DATA CONNECTED" : "MT5 DATA REQUIRED"}</div></div>
    {!connected && <div className="flex items-start gap-3 rounded-xl border border-warning/30 bg-warning/5 p-4"><CircleAlert className="mt-0.5 h-5 w-5 shrink-0 text-warning" /><div><p className="text-sm font-bold">Strategy execution is locked</p><p className="mt-1 text-xs text-muted-foreground">The controls below can be prepared, but no signal or order will be generated without live broker data from your connected MT5 account.</p></div></div>}
    <div className="grid gap-5 xl:grid-cols-[1.4fr_0.8fr]">
      <section className="rounded-xl border border-border bg-card shadow-card"><div className="flex items-center justify-between border-b border-border px-4 py-3"><div className="flex items-center gap-2 text-sm font-bold"><Layers3 className="h-4 w-4 text-primary" /> Strategy engines</div><button className="flex items-center gap-1 rounded-lg border border-border px-3 py-1.5 text-xs font-bold text-primary hover:bg-primary/10"><Plus className="h-3.5 w-3.5" /> Custom strategy</button></div><div className="grid gap-3 p-4 md:grid-cols-3">{strategyTemplates.map((template) => { const Icon = template.icon; const active = enabled[template.name] ?? false; return <div key={template.name} className={cn("rounded-xl border p-4 transition-colors", active ? "border-primary/50 bg-primary/5" : "border-border bg-background/40")}><div className="flex items-start justify-between"><div className={cn("rounded-lg bg-muted p-2", template.color)}><Icon className="h-5 w-5" /></div><button onClick={() => setEnabled((current) => ({ ...current, [template.name]: !active }))} aria-label={`${active ? "Disable" : "Enable"} ${template.name}`} className={cn("relative h-6 w-11 rounded-full transition-colors", active ? "bg-primary" : "bg-muted")}><span className={cn("absolute top-1 h-4 w-4 rounded-full bg-white transition-transform", active ? "left-6" : "left-1")} /></button></div><h2 className="mt-4 text-sm font-bold">{template.name}</h2><p className="mt-1 min-h-12 text-xs leading-5 text-muted-foreground">{template.description}</p><div className="mt-4 flex items-center gap-1 text-[10px] font-bold uppercase tracking-wide text-muted-foreground">{active ? <><Check className="h-3 w-3 text-success" /> Ready for live data</> : <><Pause className="h-3 w-3" /> Paused</>}</div></div>; })}</div></section>
      <section className="rounded-xl border border-border bg-card shadow-card"><div className="flex items-center gap-2 border-b border-border px-4 py-3 text-sm font-bold"><SlidersHorizontal className="h-4 w-4 text-primary" /> Execution settings</div><div className="space-y-5 p-4"><label className="block text-xs font-semibold">Symbols<input value={symbols} onChange={(e) => setSymbols(e.target.value)} className="mt-1.5 w-full rounded-lg border border-input bg-background px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-primary" /><span className="mt-1 block text-[10px] font-normal text-muted-foreground">Use broker symbol names exactly as provided by MT5.</span></label><label className="block text-xs font-semibold">Analysis timeframe<select value={timeframe} onChange={(e) => setTimeframe(e.target.value)} className="mt-1.5 w-full rounded-lg border border-input bg-background px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-primary"><option>M1</option><option>M5</option><option>M15</option><option>H1</option><option>H4</option></select></label><label className="block text-xs font-semibold">Risk per trade (%)<input value={risk} onChange={(e) => setRisk(e.target.value)} inputMode="decimal" className="mt-1.5 w-full rounded-lg border border-input bg-background px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-primary" /></label><div className="flex items-start gap-2 rounded-lg bg-muted/60 p-3 text-[11px] text-muted-foreground"><Gauge className="mt-0.5 h-4 w-4 shrink-0 text-primary" />Risk controls are applied server-side before any order request is sent.</div><button disabled={!connected} className="flex w-full items-center justify-center gap-2 rounded-lg bg-primary py-2.5 text-sm font-bold text-primary-foreground disabled:cursor-not-allowed disabled:opacity-40"><Play className="h-4 w-4" /> Start selected engines</button></div></section>
    </div>
    <section className="rounded-xl border border-border bg-card shadow-card"><div className="flex items-center justify-between border-b border-border px-4 py-3"><div className="flex items-center gap-2 text-sm font-bold"><Bot className="h-4 w-4 text-primary" /> Live signal stream</div><span className="rounded-full bg-muted px-2 py-1 text-[10px] font-bold text-muted-foreground">NO LIVE SIGNALS</span></div><div className="flex min-h-40 items-center justify-center p-5 text-center"><div><LockKeyhole className="mx-auto h-7 w-7 text-muted-foreground" /><p className="mt-3 text-sm font-semibold">Waiting for verified market telemetry</p><p className="mt-1 text-xs text-muted-foreground">When connected, confirmed signals for {symbols || "your selected symbols"} on {timeframe} will appear here.</p><button className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-primary hover:underline">View risk settings <ChevronRight className="h-3.5 w-3.5" /></button></div></div></section>
  </div></DashboardLayout>;
}
